// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieWebsite.Data;

#nullable disable

namespace MovieWebsite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251125053445_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieWebsite.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = "CT1",
                            CategoryName = "Âm Nhạc"
                        },
                        new
                        {
                            CategoryId = "CT2",
                            CategoryName = "Chiến Tranh"
                        },
                        new
                        {
                            CategoryId = "CT3",
                            CategoryName = "Cổ Trang"
                        },
                        new
                        {
                            CategoryId = "CT4",
                            CategoryName = "Gia Đình"
                        },
                        new
                        {
                            CategoryId = "CT5",
                            CategoryName = "Hài Hước"
                        },
                        new
                        {
                            CategoryId = "CT6",
                            CategoryName = "Hành Động"
                        },
                        new
                        {
                            CategoryId = "CT7",
                            CategoryName = "Khoa Học"
                        },
                        new
                        {
                            CategoryId = "CT8",
                            CategoryName = "Kinh Dị"
                        },
                        new
                        {
                            CategoryId = "CT9",
                            CategoryName = "Lãng Mạn"
                        },
                        new
                        {
                            CategoryId = "CT10",
                            CategoryName = "Phim Lẻ"
                        },
                        new
                        {
                            CategoryId = "CT11",
                            CategoryName = "TV Shows"
                        });
                });

            modelBuilder.Entity("MovieWebsite.Models.Comment", b =>
                {
                    b.Property<string>("CommentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MovieId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CommentId");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("MovieWebsite.Models.Favorite", b =>
                {
                    b.Property<string>("FavoriteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("MovieId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FavoriteId");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("MovieWebsite.Models.Movie", b =>
                {
                    b.Property<string>("MovieId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("Duration")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("RealeaseAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = "MV001",
                            Country = "Vietnam",
                            CreatedAt = new DateTime(2025, 5, 6, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The Avengers assemble once again to stop Thanos from destroying the universe.",
                            Duration = "181 minutes",
                            RealeaseAt = new DateTime(2025, 5, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ThumbnailUrl = "/images/phim1.png",
                            Title = "Avengers: Endgame",
                            VideoUrl = "https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ"
                        },
                        new
                        {
                            MovieId = "MV002",
                            Country = "Vietnam",
                            CreatedAt = new DateTime(2025, 5, 6, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A thief who steals corporate secrets through the use of dream-sharing technology.",
                            Duration = "148 minutes",
                            RealeaseAt = new DateTime(2025, 5, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ThumbnailUrl = "/images/phim2.png",
                            Title = "Inception",
                            VideoUrl = "https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ"
                        },
                        new
                        {
                            MovieId = "MV003",
                            Country = "Ấn Độ",
                            CreatedAt = new DateTime(2023, 4, 1, 12, 2, 0, 0, DateTimeKind.Unspecified),
                            Description = "Batman faces his most personal and dangerous challenge yet: the Joker, a criminal mastermind who wants to bring Gotham to its knees.",
                            Duration = "152 minutes",
                            RealeaseAt = new DateTime(2008, 5, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ThumbnailUrl = "/images/phim3.png",
                            Title = "The Dark Knight",
                            VideoUrl = "https://www.youtube.com/watch?v=YQ6JRqzpASM"
                        },
                        new
                        {
                            MovieId = "MV004",
                            Country = "Nhật Bản",
                            CreatedAt = new DateTime(2023, 4, 1, 12, 3, 0, 0, DateTimeKind.Unspecified),
                            Description = "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
                            Duration = "169 minutes",
                            RealeaseAt = new DateTime(2008, 5, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ThumbnailUrl = "/images/phim4.jpg",
                            Title = "Interstellar",
                            VideoUrl = "https://www.youtube.com/watch?v=example4"
                        },
                        new
                        {
                            MovieId = "MV005",
                            Country = "Nhật Bản",
                            CreatedAt = new DateTime(2023, 4, 1, 12, 4, 0, 0, DateTimeKind.Unspecified),
                            Description = "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor.",
                            Duration = "126 minutes",
                            RealeaseAt = new DateTime(2008, 5, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ThumbnailUrl = "/images/phim5.jpg",
                            Title = "Iron Man",
                            VideoUrl = "https://www.youtube.com/watch?v=example5"
                        },
                        new
                        {
                            MovieId = "MV006",
                            Country = "Nhật Bản",
                            CreatedAt = new DateTime(2023, 4, 1, 12, 5, 0, 0, DateTimeKind.Unspecified),
                            Description = "Political involvement in the Avengers' affairs causes a rift between Captain America and Iron Man.",
                            Duration = "147 minutes",
                            RealeaseAt = new DateTime(2008, 5, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ThumbnailUrl = "/images/phim6.jpg",
                            Title = "Captain America: Civil War",
                            VideoUrl = "https://www.youtube.com/watch?v=example6"
                        },
                        new
                        {
                            MovieId = "MV007",
                            Country = "Hoa Kì",
                            CreatedAt = new DateTime(2023, 4, 1, 12, 6, 0, 0, DateTimeKind.Unspecified),
                            Description = "While on a journey of physical and spiritual healing, a brilliant neurosurgeon is drawn into the world of the mystic arts.",
                            Duration = "115 minutes",
                            RealeaseAt = new DateTime(2008, 5, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ThumbnailUrl = "/images/phim7.jpg",
                            Title = "Doctor Strange",
                            VideoUrl = "https://www.youtube.com/watch?v=example7"
                        },
                        new
                        {
                            MovieId = "MV008",
                            Country = "Hoa Kì",
                            CreatedAt = new DateTime(2023, 4, 1, 12, 7, 0, 0, DateTimeKind.Unspecified),
                            Description = "T'Challa returns home to the African nation of Wakanda to take his rightful place as king.",
                            Duration = "134 minutes",
                            RealeaseAt = new DateTime(2008, 5, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ThumbnailUrl = "/images/phim8.jpg",
                            Title = "Black Panther",
                            VideoUrl = "https://www.youtube.com/watch?v=example8"
                        },
                        new
                        {
                            MovieId = "MV009",
                            Country = "Hoa Kì",
                            CreatedAt = new DateTime(2023, 4, 1, 12, 8, 0, 0, DateTimeKind.Unspecified),
                            Description = "A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.",
                            Duration = "121 minutes",
                            RealeaseAt = new DateTime(2008, 5, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ThumbnailUrl = "/images/phim9.jpg",
                            Title = "Guardians of the Galaxy",
                            VideoUrl = "https://www.youtube.com/watch?v=example9"
                        },
                        new
                        {
                            MovieId = "MV010",
                            Country = "Trung Quốc",
                            CreatedAt = new DateTime(2023, 4, 1, 12, 9, 0, 0, DateTimeKind.Unspecified),
                            Description = "Thor must escape the alien planet Sakaar in time to save Asgard from Hela and the impending Ragnarok.",
                            Duration = "130 minutes",
                            RealeaseAt = new DateTime(2008, 5, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ThumbnailUrl = "/images/phim10.jpg",
                            Title = "Thor: Ragnarok",
                            VideoUrl = "https://www.youtube.com/watch?v=example10"
                        },
                        new
                        {
                            MovieId = "MV011",
                            Country = "Trung Quốc",
                            CreatedAt = new DateTime(2023, 4, 1, 12, 10, 0, 0, DateTimeKind.Unspecified),
                            Description = "Peter Parker tries to fix everything after his identity is revealed, but ends up facing multiversal consequences.",
                            Duration = "148 minutes",
                            RealeaseAt = new DateTime(2008, 5, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ThumbnailUrl = "/images/phim11.jpg",
                            Title = "Spider-Man: No Way Home",
                            VideoUrl = "https://www.youtube.com/watch?v=example11"
                        },
                        new
                        {
                            MovieId = "MV012",
                            Country = "Hàn Quốc",
                            CreatedAt = new DateTime(2023, 4, 1, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Description = "A hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
                            Duration = "136 minutes",
                            RealeaseAt = new DateTime(2008, 5, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ThumbnailUrl = "/images/phim12.jpg",
                            Title = "The Matrix",
                            VideoUrl = "https://www.youtube.com/watch?v=example12"
                        },
                        new
                        {
                            MovieId = "MV013",
                            Country = "Hàn Quốc",
                            CreatedAt = new DateTime(2023, 4, 1, 12, 12, 0, 0, DateTimeKind.Unspecified),
                            Description = "A mentally troubled stand-up comedian embarks on a downward spiral that leads to the creation of an iconic villain.",
                            Duration = "122 minutes",
                            RealeaseAt = new DateTime(2008, 5, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ThumbnailUrl = "/images/phim13.jpg",
                            Title = "Joker",
                            VideoUrl = "https://www.youtube.com/watch?v=example13"
                        },
                        new
                        {
                            MovieId = "MV014",
                            Country = "Hàn Quốc",
                            CreatedAt = new DateTime(2023, 4, 1, 12, 13, 0, 0, DateTimeKind.Unspecified),
                            Description = "Armed with only one word, Tenet, a protagonist fights for the survival of the world.",
                            Duration = "150 minutes",
                            RealeaseAt = new DateTime(2008, 5, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ThumbnailUrl = "/images/phim14.jpg",
                            Title = "Tenet",
                            VideoUrl = "https://www.youtube.com/watch?v=example14"
                        },
                        new
                        {
                            MovieId = "MV015",
                            Country = "Vietnam",
                            CreatedAt = new DateTime(2023, 4, 1, 12, 14, 0, 0, DateTimeKind.Unspecified),
                            Description = "Paul Atreides leads nomadic tribes in a battle to control the desert planet Arrakis.",
                            Duration = "155 minutes",
                            RealeaseAt = new DateTime(2008, 5, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ThumbnailUrl = "/images/phim15.jpg",
                            Title = "Dune",
                            VideoUrl = "https://www.youtube.com/watch?v=example15"
                        },
                        new
                        {
                            MovieId = "MV016",
                            Country = "Vietnam",
                            CreatedAt = new DateTime(2025, 4, 1, 12, 15, 0, 0, DateTimeKind.Unspecified),
                            Description = "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following orders and protecting an alien civilization.",
                            Duration = "162 minutes",
                            RealeaseAt = new DateTime(2008, 5, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ThumbnailUrl = "/images/phim16.jpg",
                            Title = "Avatar",
                            VideoUrl = "https://www.youtube.com/watch?v=example16"
                        },
                        new
                        {
                            MovieId = "MV017",
                            Country = "Vietnam",
                            CreatedAt = new DateTime(2025, 4, 1, 12, 16, 0, 0, DateTimeKind.Unspecified),
                            Description = "Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.",
                            Duration = "132 minutes",
                            RealeaseAt = new DateTime(2008, 5, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ThumbnailUrl = "/images/phim17.jpg",
                            Title = "Shang-Chi and the Legend of the Ten Rings",
                            VideoUrl = "https://www.youtube.com/watch?v=example17"
                        },
                        new
                        {
                            MovieId = "MV018",
                            Country = "Vietnam",
                            CreatedAt = new DateTime(2025, 4, 1, 12, 17, 0, 0, DateTimeKind.Unspecified),
                            Description = "The saga of the Eternals, a race of immortal beings who lived on Earth and shaped its history and civilizations.",
                            Duration = "157 minutes",
                            RealeaseAt = new DateTime(2008, 5, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ThumbnailUrl = "/images/phim18.jpg",
                            Title = "Eternals",
                            VideoUrl = "https://www.youtube.com/watch?v=example18"
                        },
                        new
                        {
                            MovieId = "MV019",
                            Country = "Vietnam",
                            CreatedAt = new DateTime(2025, 4, 1, 12, 18, 0, 0, DateTimeKind.Unspecified),
                            Description = "Batman ventures into Gotham City's underworld when a sadistic killer leaves behind a trail of cryptic clues.",
                            Duration = "176 minutes",
                            RealeaseAt = new DateTime(2008, 5, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ThumbnailUrl = "/images/phim19.jpg",
                            Title = "The Batman",
                            VideoUrl = "https://www.youtube.com/watch?v=example19"
                        },
                        new
                        {
                            MovieId = "MV020",
                            Country = "Vietnam",
                            CreatedAt = new DateTime(2025, 4, 1, 12, 19, 0, 0, DateTimeKind.Unspecified),
                            Description = "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos.",
                            Duration = "149 minutes",
                            RealeaseAt = new DateTime(2008, 5, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ThumbnailUrl = "/images/phim20.jpg",
                            Title = "Avengers: Infinity War",
                            VideoUrl = "https://www.youtube.com/watch?v=example20"
                        },
                        new
                        {
                            MovieId = "MV021",
                            Country = "Japan",
                            CreatedAt = new DateTime(2025, 5, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Luffy",
                            Duration = "23 minutes",
                            RealeaseAt = new DateTime(2025, 5, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ThumbnailUrl = "/images/phim21.jpg",
                            Title = "Onepiece tap 419",
                            VideoUrl = "https://www.youtube.com/embed/df5mticutx8"
                        });
                });

            modelBuilder.Entity("MovieWebsite.Models.MovieCategory", b =>
                {
                    b.Property<string>("MovieId")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MovieId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("MovieCategories");

                    b.HasData(
                        new
                        {
                            MovieId = "MV001",
                            CategoryId = "CT6"
                        },
                        new
                        {
                            MovieId = "MV001",
                            CategoryId = "CT10"
                        },
                        new
                        {
                            MovieId = "MV002",
                            CategoryId = "CT7"
                        },
                        new
                        {
                            MovieId = "MV003",
                            CategoryId = "CT6"
                        },
                        new
                        {
                            MovieId = "MV003",
                            CategoryId = "CT8"
                        },
                        new
                        {
                            MovieId = "MV004",
                            CategoryId = "CT7"
                        },
                        new
                        {
                            MovieId = "MV005",
                            CategoryId = "CT6"
                        },
                        new
                        {
                            MovieId = "MV006",
                            CategoryId = "CT2"
                        },
                        new
                        {
                            MovieId = "MV006",
                            CategoryId = "CT6"
                        },
                        new
                        {
                            MovieId = "MV007",
                            CategoryId = "CT7"
                        },
                        new
                        {
                            MovieId = "MV008",
                            CategoryId = "CT4"
                        },
                        new
                        {
                            MovieId = "MV009",
                            CategoryId = "CT11"
                        },
                        new
                        {
                            MovieId = "MV010",
                            CategoryId = "CT6"
                        },
                        new
                        {
                            MovieId = "MV011",
                            CategoryId = "CT10"
                        },
                        new
                        {
                            MovieId = "MV012",
                            CategoryId = "CT7"
                        },
                        new
                        {
                            MovieId = "MV013",
                            CategoryId = "CT8"
                        },
                        new
                        {
                            MovieId = "MV014",
                            CategoryId = "CT7"
                        },
                        new
                        {
                            MovieId = "MV015",
                            CategoryId = "CT7"
                        },
                        new
                        {
                            MovieId = "MV015",
                            CategoryId = "CT5"
                        },
                        new
                        {
                            MovieId = "MV016",
                            CategoryId = "CT7"
                        },
                        new
                        {
                            MovieId = "MV017",
                            CategoryId = "CT6"
                        },
                        new
                        {
                            MovieId = "MV017",
                            CategoryId = "CT10"
                        },
                        new
                        {
                            MovieId = "MV018",
                            CategoryId = "CT7"
                        },
                        new
                        {
                            MovieId = "MV019",
                            CategoryId = "CT8"
                        },
                        new
                        {
                            MovieId = "MV020",
                            CategoryId = "CT6"
                        });
                });

            modelBuilder.Entity("MovieWebsite.Models.Rating", b =>
                {
                    b.Property<string>("RatingId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MovieId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("RateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RatingId");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("MovieWebsite.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("TokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VerificationToken")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = "U001",
                            AvatarUrl = "/images/avt_macdinh.jpg",
                            CreatedAt = new DateTime(2023, 4, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@example.com",
                            IsVerified = true,
                            PasswordHash = "$2a$12$4UBBXElUopV4./fG2gNQJeVZnbRTI7dqpTUOW0ORZjp0eY35AAreW",
                            Role = "admin",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("MovieWebsite.Models.WatchHistory", b =>
                {
                    b.Property<string>("WatchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MovieId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("WatchedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("WatchId");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("WatchHistories");
                });

            modelBuilder.Entity("MovieWebsite.Models.Comment", b =>
                {
                    b.HasOne("MovieWebsite.Models.Movie", "Movie")
                        .WithMany("Comments")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieWebsite.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieWebsite.Models.Favorite", b =>
                {
                    b.HasOne("MovieWebsite.Models.Movie", "Movie")
                        .WithMany("Favorites")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieWebsite.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieWebsite.Models.MovieCategory", b =>
                {
                    b.HasOne("MovieWebsite.Models.Category", "Category")
                        .WithMany("MovieCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieWebsite.Models.Movie", "Movie")
                        .WithMany("MovieCategories")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieWebsite.Models.Rating", b =>
                {
                    b.HasOne("MovieWebsite.Models.Movie", "Movie")
                        .WithMany("Ratings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieWebsite.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieWebsite.Models.WatchHistory", b =>
                {
                    b.HasOne("MovieWebsite.Models.Movie", "Movie")
                        .WithMany("WatchHistories")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieWebsite.Models.User", "User")
                        .WithMany("WatchHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieWebsite.Models.Category", b =>
                {
                    b.Navigation("MovieCategories");
                });

            modelBuilder.Entity("MovieWebsite.Models.Movie", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Favorites");

                    b.Navigation("MovieCategories");

                    b.Navigation("Ratings");

                    b.Navigation("WatchHistories");
                });

            modelBuilder.Entity("MovieWebsite.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Favorites");

                    b.Navigation("Ratings");

                    b.Navigation("WatchHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
